### ISSUE TITLE
Combobox does not render correctly and does not function

### ISSUE THREAD

**Issue by musa11971** [sertxudeveloper/livewire-combobox#26]
Steps to replicate:
1. Create a Laravel app, use Vite & tailwind css.
2. Install the package `composer require sertxudeveloper/livewire-combobox`
3. Create a combobox `php artisan combobox:make ApplicationsCombobox -m Application`
4. Use the combobox
```html
<x-form.group label="Application" required class="mb-4">
        <livewire:applications-combobox />

        <x-form.error name="form.application_id"></x-form.error>
</x-form.group>
```
5. The combobox will not render properly, nor will it function.

![Screenshot 2024-11-19 at 11 46 03](https://github.com/user-attachments/assets/d77f7a62-1cb7-42af-ab47-ab3229321885)

Verified:
- A model named `Application` exists, and it has a `name` property.
- Tailwind css is installed.
- PHP version 8.3
- `"livewire/livewire": "^3.5.12",`
- `"laravel/framework": "^11.31",`

**Comment by sertxudev** [comment]
Hi @musa11971
I developed this package for a project which is still using Livewire 2.

My idea was to update this package to fully support Livewire 3, but priorities changed few times and now it's a legacy project.

Also Caleb released https://fluxui.dev which supports Comboboxes and more Livewire components, so probably I will end up archiving this repository as I no longer need it since I own an Unlimited license.

Feel free to send a pull request if you found a fix in the meantime.

**Comment by musa11971** [comment]
Thanks for the heads up @sertxudev. I've decided to create my own component since it better fit my needs. Perhaps the repository should indeed be archived if the Livewire version is outdated and no active maintenance is being performed.
